// test/integration/dev-alpha4-composition.test.js —
// Alpha 4 dev-profile composition integration test.
//
// Asserts the plugin's effective behavior in a real `dsh --profile dev`
// composition under DSH 0.1.2-alpha.4. Specifically:
//   - tool-web.disabled === false
//   - tool-web.config.fetch === true
//   - web-search-deepseek.disabled === true
//   - web.searchProvider === 'web-access-chain-search'
//   - web.fetchProvider  === 'web-access-chain-fetch'
//
// The test auto-skips when the dev profile is not present (CI /
// contributor machines without the audit dev profile). To enable it,
// set up the dev profile per docs/dsh-alpha4-compatibility-plan.md §1.1.
//
// No paid providers, no LLM, no network beyond what the composition
// itself exercises.

import { test } from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

// DSH_HOME may point at the harness home itself (in which case dev
// lives under `${DSH_HOME}/profiles/dev`) or may be unset (in which
// case dev lives under `~/.dsh/profiles/dev`). Be careful not to
// double-append `.dsh` when DSH_HOME is set.
const DSH_BASE = process.env.DSH_HOME || join(homedir(), '.dsh')
const DEV_PROFILE = join(DSH_BASE, 'profiles', 'dev')

function devProfileExists() {
  return existsSync(join(DEV_PROFILE, 'package.json'))
}

function readDevDumpConfig() {
  // Dump the dev profile composition. `dsh --dump-config` writes to
  // stdout and exits 0 on success. The dev profile must already be
  // initialized and contain the plugin (per docs/dsh-alpha4-compatibility-plan.md).
  const out = execFileSync('dsh', ['--dump-config', '--profile', 'dev'], {
    cwd: DEV_PROFILE,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  return out
}

// Extract the effective row for a given `id` from the dumped YAML.
// This is a small, tolerant parser — the dump is generated by dsh
// and the shape is stable enough for these five invariants.
function findRow(yaml, id) {
  // The dump is a YAML list. Find a top-level `- id: <id>` and capture
  // the indented sub-keys that follow.
  const lines = yaml.split('\n')
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    if (!new RegExp(`^- id:\\s*${id}\\s*$`).test(line)) continue
    const row = { __id: id, __startLine: i, fields: {} }
    for (let j = i + 1; j < lines.length; j++) {
      const sub = lines[j]
      // next top-level row or section header
      if (/^- id:\s/.test(sub) || /^# ==/.test(sub)) break
      const m = sub.match(/^  (\w[\w-]*):\s*(.*)$/)
      if (m) row.fields[m[1]] = m[2]
    }
    return row
  }
  return null
}

test('Alpha 4 dev composition: tool-web row has disabled=false and config.fetch=true', (t) => {
  if (!devProfileExists()) {
    t.skip(`dev profile not found at ${DEV_PROFILE}; see docs/dsh-alpha4-compatibility-plan.md §1.1 to enable`)
    return
  }
  const yaml = readDevDumpConfig()
  const row = findRow(yaml, 'tool-web')
  assert.ok(row, 'tool-web row must be present in dev composition')
  assert.equal(row.fields.disabled, 'false',
    `tool-web.disabled must be false; got ${JSON.stringify(row.fields.disabled)}`)
  // config.fetch appears under the tool-web block as a nested map;
  // the dsh dump renders it like:
  //   config:
  //     fetch: true
  // which our flat parser folds into fields. We confirm it is present
  // by scanning the sub-block directly.
  const sub = yaml.split('\n').slice(row.__startLine, row.__startLine + 10).join('\n')
  assert.match(sub, /config:\s*\n\s+fetch:\s*true/,
    'tool-web.config.fetch must be true (alpha.4 base default) under dev composition')
})

test('Alpha 4 dev composition: web-search-deepseek row is disabled', (t) => {
  if (!devProfileExists()) {
    t.skip(`dev profile not found at ${DEV_PROFILE}`)
    return
  }
  const yaml = readDevDumpConfig()
  const row = findRow(yaml, 'web-search-deepseek')
  assert.ok(row, 'web-search-deepseek row must be present in dev composition')
  assert.equal(row.fields.disabled, 'true',
    `web-search-deepseek.disabled must be true; got ${JSON.stringify(row.fields.disabled)}`)
})

test('Alpha 4 dev composition: web.searchProvider / web.fetchProvider point to the plugin', (t) => {
  if (!devProfileExists()) {
    t.skip(`dev profile not found at ${DEV_PROFILE}`)
    return
  }
  const yaml = readDevDumpConfig()
  const row = findRow(yaml, 'web')
  assert.ok(row, 'web row must be present in dev composition')
  // The dump nests the `config` map; flatten it by scanning the sub-block.
  const sub = yaml.split('\n').slice(row.__startLine, row.__startLine + 12).join('\n')
  assert.match(sub, /searchProvider:\s*web-access-chain-search/,
    'web.searchProvider must be web-access-chain-search')
  assert.match(sub, /fetchProvider:\s*web-access-chain-fetch/,
    'web.fetchProvider must be web-access-chain-fetch')
})

// Sanity: the dev profile's own `cordis.patch.yml` no longer needs the
// `tool-web: disabled: false` overlay (the plugin's own patch now
// supplies it). If the dev overlay still exists, that is fine — it
// is redundant but harmless. This assertion documents the redundancy
// so future cleanups know what to look for.
test('Alpha 4 dev composition: dev cordis.patch.yml tool-web overlay is redundant (informational)', (t) => {
  if (!devProfileExists()) {
    t.skip(`dev profile not found at ${DEV_PROFILE}`)
    return
  }
  const overlayPath = join(DEV_PROFILE, 'cordis.patch.yml')
  if (!existsSync(overlayPath)) {
    t.skip(`dev profile has no cordis.patch.yml at ${overlayPath}`)
    return
  }
  const overlay = readFileSync(overlayPath, 'utf8')
  // The plugin's own patch now re-enables tool-web. The dev profile's
  // own overlay is allowed to be redundant; this test does not fail
  // on it. It only records a note for the audit trail.
  if (/^-\s*id:\s*tool-web\s*\n\s*disabled:\s*false/m.test(overlay)) {
    // ok — redundant, but documented.
    t.diagnostic('dev profile has its own `tool-web: disabled: false` overlay; redundant after the plugin patch fix; safe to remove in a follow-up cleanup.')
  } else {
    t.diagnostic('dev profile has no tool-web overlay; clean state.')
  }
})
